# Generated by Django 4.1.7 on 2023-07-03 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("notice", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
