# Generated by Django 4.1.7 on 2023-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
