# Generated by Django 4.1.7 on 2023-07-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="source",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="notice",
            field=models.TextField(null=True),
        ),
    ]
