# Generated by Django 4.1.7 on 2023-07-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0002_announcement_source_alter_announcement_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="notice",
            field=models.TextField(default="Example notice...."),
        ),
    ]
