# Generated by Django 4.1.7 on 2023-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0005_alter_complaints_roomno"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaints",
            name="msg",
            field=models.TextField(null=True),
        ),
    ]
