# Generated by Django 4.1.7 on 2023-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0006_complaints_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaints",
            name="idno",
            field=models.IntegerField(default=2100032351),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="msg",
            field=models.TextField(default="Enter msg"),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="query",
            field=models.TextField(default="Enter query"),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="roomno",
            field=models.TextField(default="313"),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="teamno",
            field=models.IntegerField(default=1),
        ),
    ]
