# Generated by Django 4.1.7 on 2023-07-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0007_alter_complaints_idno_alter_complaints_msg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaints",
            name="idno",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="msg",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="query",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="roomno",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="complaints",
            name="teamno",
            field=models.TextField(),
        ),
    ]
