# Generated by Django 4.1.7 on 2023-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0009_room_session_team_teacher_student_review_attendence"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=30)),
                ("pdf", models.ImageField(upload_to="media/pdfs")),
            ],
        ),
    ]
