# Generated by Django 4.1.7 on 2023-07-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0010_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="pdf",
            field=models.FileField(upload_to="media/pdfs"),
        ),
    ]
