# Generated by Django 4.1.7 on 2023-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0013_alter_timetable_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="pdf",
            field=models.FileField(upload_to="static/timetables"),
        ),
    ]
