# Generated by Django 4.1.7 on 2023-07-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0014_alter_timetable_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
