# Generated by Django 4.1.7 on 2023-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0016_remove_team_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
