# Generated by Django 4.1.7 on 2023-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0017_room_submitted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="submitted",
        ),
        migrations.AddField(
            model_name="team",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
