# Generated by Django 4.1.7 on 2023-07-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0020_review_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="room",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Website.room",
            ),
        ),
    ]
