# Generated by Django 4.1.7 on 2023-07-21 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0021_teacher_room"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Session",
            new_name="Sessions",
        ),
    ]
