# Generated by Django 4.1.7 on 2023-07-21 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0024_alter_student_user_alter_teacher_user_delete_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sessions",
            new_name="Session",
        ),
    ]
