# Generated by Django 4.1.7 on 2023-07-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0025_rename_sessions_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="pdf",
            field=models.FileField(upload_to="timetables"),
        ),
    ]
