# Generated by Django 4.1.7 on 2023-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Website", "0026_alter_timetable_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="notice",
            field=models.TextField(default=""),
        ),
    ]
